//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Future_Me.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAIL
    {
        public int ID { get; set; }
        public int IDUser { get; set; }
        public string EmailTo { get; set; }
        public string Subject { get; set; }
        public string Letter { get; set; }
        public System.DateTime DeliverOn { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
