//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Future_Me.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public USER()
        {
            this.MAILs = new HashSet<MAIL>();
        }
    
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<MAIL> MAILs { get; set; }
    }
}
